#!/usr/bin/env python3
import os
import shutil
import glob


def is_file(path):
    return os.path.isfile(path) and not os.path.islink(path)


def is_directory(path):
    return os.path.isdir(path) and not os.path.islink(path)


def is_link(path):
    return os.path.islink(path)


def main():
    targets = glob.glob('.*')
    current_dir = os.path.dirname(os.path.abspath(__file__))
    home_dir = os.path.expanduser('~')
    for target in targets:
        source = f"{current_dir}/{target}"
        destination = f"{home_dir}/{target}"
        if os.path.lexists(destination):
            print(f"{destination} already exists.\nOverwrite (y/N)? ", end='')
            if input().strip() in ['y', 'Y']:
                if is_file(destination):
                    os.remove(destination)
                if is_directory(destination):
                    shutil.rmtree(destination)
                if is_link(destination):
                    os.unlink(destination)
            else:
                continue
        print(f"{destination} -> {source}")
        os.symlink(source, destination)


if __name__ == '__main__':
    main()
